# Generated by Django 5.0.2 on 2024-02-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('create_date', models.CharField(max_length=100)),
            ],
        ),
    ]
